ci:
  skip: [clang-format]

exclude: (?:^hoomd/extern/)

repos:
- repo: local
  hooks:
  - id: make_workflows
    name: make_workflows
    language: python
    entry: python3 .github/workflows/make_workflows.py
    pass_filenames: false
    always_run: true
    additional_dependencies: [jinja2==2.11.3, pyyaml==5.4.1]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.4.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-json
  - id: check-yaml
    exclude: (?:^.github/workflows/templates) # templates are not properly formatted yaml
  - id: check-case-conflict
- repo: https://github.com/google/yapf
  rev: 'v0.31.0'
  hooks:
  - id: yapf
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.1'
  hooks:
  - id: flake8
    # This option may be useful after we get HOOMD to 0 flake8 errors
    # args:
    # - --show-source
    additional_dependencies:
    - pep8-naming
    - flake8-docstrings
    - flake8-rst-docstrings
    # exclude components yet yet ported to hoomd
    # TODO: Remove these exclusions as components are ported
    exclude: |
      (?x)(
        ^hoomd/extern/|
        ^hoomd/mpcd/|
        ^hoomd/dem/|
        ^hoomd/jit/|
        ^hoomd/metal/|
        ^hoomd/minimize/|
        ^doc/dev/
      )
- repo: https://github.com/glotzerlab/pre-commit-clang-format
  rev: v1.1.0
  hooks:
  - id: clang-format
    stages: [manual]
    exclude: |
      (?x)(
        ^CMake/|
        ^hoomd/extern/|
        ^hoomd/hpmc/UpdaterClusters\.h|
        ^hoomd/hpmc/IntegratorHPMCMono\.h|
        ^doc/dev/
      )
