# configurations to build and test on every pull request
# each entry is a mapping with:
# - config: a string encoded list containing the docker image name and any number of build options.
# - The build options are `mpi`, `tbb`, `llvm`, `nomd`, and `nohpmc`.
unit_test_configurations:
- config: "[clang18_py312, mpi, tbb]"
- config: "[gcc14_py312]"
- config: "[gcc14_py312, nomd]"
- config: "[gcc14_py312, nohpmc]"
- config: "[gcc14_py312, nomd, nohpmc]"
- config: "[cuda120_gcc11_py310, mpi, llvm, debug]"
- config: "[cuda120_gcc11_py310, mpi, llvm]"
- config: "[cuda120_gcc11_py310]"
- config: "[gcc9_py39]"

# Configurations on which to run longer validation tests. Must be a subset of
# `unit_test_configurations`
validate_configurations:
- config: "[clang18_py311, mpi, tbb]"
- config: "[gcc14_py312]"
- config: "[cuda120_gcc11_py310, mpi, llvm]"
- config: "[cuda120_gcc11_py310]"

# Configurations to build and test only rarely, such as just before a release.
# There should be no overlap between this list and `unit_test_configurations`
release_test_configurations:
- config: "[clang17_py312, mpi, llvm]"
- config: "[clang16_py312, mpi, llvm]"
- config: "[clang15_py312, mpi, llvm]"
- config: "[clang14_py311, mpi, llvm]"
- config: "[clang13_py310, llvm]"
- config: "[clang12_py310, llvm]"
- config: "[clang11_py310, llvm]"
- config: "[gcc13_py312]"
- config: "[gcc12_py311]"
- config: "[gcc11_py310]"
- config: "[gcc10_py310]"
- config: "[cuda118_gcc11_py310, mpi, llvm]"
- config: "[cuda117_gcc11_py310, mpi, llvm]"
