<% block name %><% endblock %>
<% set container_prefix="glotzerlab/ci:2024.03.01" %>

<% block concurrency %>
concurrency:
  <% block concurrency_group %>
  group: ${{ github.workflow }}-${{ github.ref }}
  <% endblock %>
  <% block concurrency_cancel_in_progress %>
  cancel-in-progress: true
  <% endblock %>
<% endblock %>

<% block on %>
on:
  <% block on_pull_request %>
  # Trigger on pull requests.
  pull_request:
  <% endblock %>

  <% block on_push %>
  # Trigger on pushes to the trunk branches. This prevents building commits twice when the pull
  # request source branch is in the same repository.
  push:
    <% block on_push_branches %>
    branches:
    - "trunk-*"
    <% endblock %>
    <% block on_push_tags %>
    <% endblock %>
  <% endblock %>

  <% block on_workflow_dispatch %>
  # Trigger on request.
  workflow_dispatch:
  <% endblock %>
<% endblock %>

<% block permissions %>
<% endblock %>

<% block env %>
<% endblock %>

<% block defaults %>
<% endblock %>

<% block jobs %>
<% endblock %>
