version: 2.1

executors:
  glotzerlab:
    parameters:
      image:
        type: string
    docker:
      - image: glotzerlab/ci:2019.06-<< parameters.image >>
    working_directory: /home/ci/project

jobs:
  build_and_test:
    parameters:
      image:
        type: string
    executor:
      name: glotzerlab
      image: << parameters.image >>
    steps:
      - run:
          name: No-op
          command: echo "Testing now performed by azure pipelines: https://dev.azure.com/glotzerlab/hoomd-blue"

workflows:
  test:
    jobs:
      - build_and_test:
          name: noop
          image: ubuntu18.04
